# Generated by Django 3.2.16 on 2023-10-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20231023_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl\n                                  для выбора нескольких вариантов.', to='blog.Tag', verbose_name='Теги'),
        ),
    ]
